Repository 42-JMJ/iOS-App-Project, pull requests merged in 2020-05, with the labels that each got.

#38 PR 리뷰어가 헷갈려서 PR 템플릿을 만들었습니다
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 협업환경

#41 datebase로 sqlite 사용!
  OneDayOneAnswer/OneDayOneAnswer.xcodeproj/project.pbxproj
  OneDayOneAnswer/OneDayOneAnswer/42-JMJ-Question.tsv
  OneDayOneAnswer/OneDayOneAnswer/DataBase/DataBase.swift
  OneDayOneAnswer/OneDayOneAnswer/DataBase/SqliteDataBase.swift
  OneDayOneAnswer/OneDayOneAnswer/DataBase/TestDataBase.swift
  OneDayOneAnswer/OneDayOneAnswer/TodayViewController.swift
Labels: 데이터베이스

#40 Today.Storayboard 구현(4)
  OneDayOneAnswer/OneDayOneAnswer/Base.lproj/Today.storyboard
  OneDayOneAnswer/OneDayOneAnswer/Display.storyboard
  OneDayOneAnswer/OneDayOneAnswer/List.storyboard
  OneDayOneAnswer/OneDayOneAnswer/TodayViewController.swift
Labels: 뷰컨트롤러

#45 Feature/list
  OneDayOneAnswer/OneDayOneAnswer/List.storyboard
  OneDayOneAnswer/OneDayOneAnswer/ListViewController.swift
  OneDayOneAnswer/OneDayOneAnswer/TableViewCell.swift
  OneDayOneAnswer/OneDayOneAnswer/TodayViewController.swift
Labels: 뷰컨트롤러

#48 Today.Stroyboard 이미지피커 버튼추가 및 코드개선
  OneDayOneAnswer/OneDayOneAnswer.xcodeproj/project.pbxproj
  OneDayOneAnswer/OneDayOneAnswer/AppDelegate.swift
  OneDayOneAnswer/OneDayOneAnswer/Assets.xcassets/to_edit.imageset/Contents.json
  OneDayOneAnswer/OneDayOneAnswer/Assets.xcassets/to_edit.imageset/icons8-edit-file-100.png
  OneDayOneAnswer/OneDayOneAnswer/Assets.xcassets/to_list.imageset/Contents.json
  OneDayOneAnswer/OneDayOneAnswer/Assets.xcassets/to_list.imageset/icons8-top-menu-100.png
  OneDayOneAnswer/OneDayOneAnswer/Assets.xcassets/to_photolibrary.imageset/Contents.json
  OneDayOneAnswer/OneDayOneAnswer/Assets.xcassets/to_photolibrary.imageset/icons8-pictures-folder-100.png
  OneDayOneAnswer/OneDayOneAnswer/Assets.xcassets/to_save.imageset/Contents.json
  OneDayOneAnswer/OneDayOneAnswer/Assets.xcassets/to_save.imageset/icons8-checkmark-100.png
  OneDayOneAnswer/OneDayOneAnswer/Assets.xcassets/to_save_disabled.imageset/Contents.json
  OneDayOneAnswer/OneDayOneAnswer/Assets.xcassets/to_save_disabled.imageset/icons8-checkmark-100_gray.png
  OneDayOneAnswer/OneDayOneAnswer/Base.lproj/Today.storyboard
  OneDayOneAnswer/OneDayOneAnswer/DataBase/SqliteDataBase.swift
  OneDayOneAnswer/OneDayOneAnswer/DataBase/TestDataBase.swift
  OneDayOneAnswer/OneDayOneAnswer/TodayViewController.swift
  OneDayOneAnswer/OneDayOneAnswer/Utils/FileUtils.swift
  OneDayOneAnswer/OneDayOneAnswer/images/test_image.png
Labels: 뷰컨트롤러 구현

#51 Feature/list
  OneDayOneAnswer/OneDayOneAnswer/DataBase/SqliteDataBase.swift
  OneDayOneAnswer/OneDayOneAnswer/List.storyboard
  OneDayOneAnswer/OneDayOneAnswer/ListViewController.swift
  OneDayOneAnswer/OneDayOneAnswer/TableViewCell.swift
  OneDayOneAnswer/OneDayOneAnswer/TodayViewController.swift
Labels: 뷰컨트롤러 구현

#53 Feature/database
  OneDayOneAnswer/OneDayOneAnswer/DataBase/DataBase.swift
  OneDayOneAnswer/OneDayOneAnswer/DataBase/SqliteDataBase.swift
  OneDayOneAnswer/OneDayOneAnswer/Utils/FileUtils.swift
Labels: 개발, 데이터베이스

#55 Feature/list, todayViewController에 모달추가
  OneDayOneAnswer/OneDayOneAnswer/Base.lproj/LaunchScreen.storyboard
  OneDayOneAnswer/OneDayOneAnswer/Base.lproj/Today.storyboard
  OneDayOneAnswer/OneDayOneAnswer/DataBase/TestDataBase.swift
  OneDayOneAnswer/OneDayOneAnswer/DisplayViewController.swift
  OneDayOneAnswer/OneDayOneAnswer/Info.plist
  OneDayOneAnswer/OneDayOneAnswer/List.storyboard
  OneDayOneAnswer/OneDayOneAnswer/ListViewController.swift
  OneDayOneAnswer/OneDayOneAnswer/TableViewCell.swift
  OneDayOneAnswer/OneDayOneAnswer/TodayViewController.swift
Labels: 뷰컨트롤러 구현

#56 Display.Storyboard 구현(1) 전체레이아웃 설정
  OneDayOneAnswer/OneDayOneAnswer/Assets.xcassets/test_image_1.imageset/Contents.json
  OneDayOneAnswer/OneDayOneAnswer/Assets.xcassets/test_image_1.imageset/ryan-spencer-XGKaRnWjv1c-unsplash.jpg
  OneDayOneAnswer/OneDayOneAnswer/Assets.xcassets/test_image_2.imageset/Contents.json
  OneDayOneAnswer/OneDayOneAnswer/Assets.xcassets/test_image_2.imageset/oxana-v-qoAIlAmLJBU-unsplash.jpg
  OneDayOneAnswer/OneDayOneAnswer/Assets.xcassets/to_edit_white.imageset/Contents.json
  OneDayOneAnswer/OneDayOneAnswer/Assets.xcassets/to_edit_white.imageset/icons8-edit-file-100_white.png
  OneDayOneAnswer/OneDayOneAnswer/Assets.xcassets/to_list_white.imageset/Contents.json
  OneDayOneAnswer/OneDayOneAnswer/Assets.xcassets/to_list_white.imageset/icons8-top-menu-100_white.png
  OneDayOneAnswer/OneDayOneAnswer/Assets.xcassets/to_photolibrary_white.imageset/Contents.json
  OneDayOneAnswer/OneDayOneAnswer/Assets.xcassets/to_photolibrary_white.imageset/icons8-pictures-folder-100_white.png
  OneDayOneAnswer/OneDayOneAnswer/Assets.xcassets/to_save_white.imageset/Contents.json
  OneDayOneAnswer/OneDayOneAnswer/Assets.xcassets/to_save_white.imageset/icons8-checkmark-100_white.png
  OneDayOneAnswer/OneDayOneAnswer/Base.lproj/Today.storyboard
  OneDayOneAnswer/OneDayOneAnswer/DataBase/TestDataBase.swift
  OneDayOneAnswer/OneDayOneAnswer/Display.storyboard
  OneDayOneAnswer/OneDayOneAnswer/DisplayViewController.swift
  OneDayOneAnswer/OneDayOneAnswer/List.storyboard
Labels: 뷰컨트롤러 구현

#59 초기데이터를 날짜에 맞춰서 생성함
  OneDayOneAnswer/OneDayOneAnswer/DataBase/SqliteDataBase.swift
  OneDayOneAnswer/OneDayOneAnswer/DataBase/TestDataBase.swift
Labels: 개발, 데이터베이스

#60 JMJ팀 깃컨벤션 업데이트
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 협업환경

#61 Today스토리보드에 darkmode & 오토레이아웃 적용
  OneDayOneAnswer/OneDayOneAnswer/Base.lproj/Today.storyboard
  OneDayOneAnswer/OneDayOneAnswer/Display.storyboard
  OneDayOneAnswer/OneDayOneAnswer/DisplayViewController.swift
  OneDayOneAnswer/OneDayOneAnswer/ListViewController.swift
  OneDayOneAnswer/OneDayOneAnswer/TodayViewController.swift
Labels: 뷰컨트롤러 구현

#62 Feature/list
  OneDayOneAnswer/OneDayOneAnswer.xcodeproj/project.pbxproj
  OneDayOneAnswer/OneDayOneAnswer/Assets.xcassets/catcat.imageset/Contents.json
  OneDayOneAnswer/OneDayOneAnswer/Assets.xcassets/catcat.imageset/catcat.jpg
  OneDayOneAnswer/OneDayOneAnswer/Assets.xcassets/ssss.imageset/Contents.json
  OneDayOneAnswer/OneDayOneAnswer/Assets.xcassets/ssss.imageset/ssss.jpg
  OneDayOneAnswer/OneDayOneAnswer/DXPnMStd-Regular.otf
  OneDayOneAnswer/OneDayOneAnswer/Info.plist
  OneDayOneAnswer/OneDayOneAnswer/List.storyboard
  OneDayOneAnswer/OneDayOneAnswer/ListViewController.swift
  OneDayOneAnswer/OneDayOneAnswer/Opening.storyboard
  OneDayOneAnswer/OneDayOneAnswer/OpeningViewController.swift
  OneDayOneAnswer/OneDayOneAnswer/TableViewCell.swift
  OneDayOneAnswer/OneDayOneAnswer/TodayViewController.swift
Labels: 디자인

#63 Today스토리보드 darkmode적용 및 디테일 수정
  OneDayOneAnswer/OneDayOneAnswer.xcodeproj/project.pbxproj
  OneDayOneAnswer/OneDayOneAnswer/Base.lproj/Today.storyboard
  OneDayOneAnswer/OneDayOneAnswer/Display.storyboard
  OneDayOneAnswer/OneDayOneAnswer/DisplayViewController.swift
  OneDayOneAnswer/OneDayOneAnswer/Opening.storyboard
  OneDayOneAnswer/OneDayOneAnswer/OpeningViewController.swift
  OneDayOneAnswer/OneDayOneAnswer/TodayViewController.swift
Labels: 뷰컨트롤러 구현

#66 회의하며 버그 및 문구 수정
  OneDayOneAnswer/OneDayOneAnswer/Base.lproj/Today.storyboard
  OneDayOneAnswer/OneDayOneAnswer/DisplayViewController.swift
  OneDayOneAnswer/OneDayOneAnswer/List.storyboard
  OneDayOneAnswer/OneDayOneAnswer/TodayViewController.swift
Labels: 버그

#67 화면 전환 애니매이션 변경
  OneDayOneAnswer/OneDayOneAnswer/Base.lproj/Today.storyboard
  OneDayOneAnswer/OneDayOneAnswer/Display.storyboard
  OneDayOneAnswer/OneDayOneAnswer/List.storyboard
Labels: 개발, 디자인

#70 저장할때 15바이트 이하는 저장이 제대로 안되는 문제 해결
  OneDayOneAnswer/OneDayOneAnswer/DataBase/SqliteDataBase.swift
Labels: 데이터베이스, 버그

#69 Display.Storyboard 오토레이아웃 적용
  OneDayOneAnswer/OneDayOneAnswer/Assets.xcassets/to_edit.imageset/Contents.json
  OneDayOneAnswer/OneDayOneAnswer/Assets.xcassets/to_edit.imageset/icons8-edit-file-100.png
  OneDayOneAnswer/OneDayOneAnswer/Assets.xcassets/to_edit_white.imageset/Contents.json
  OneDayOneAnswer/OneDayOneAnswer/Assets.xcassets/to_edit_white.imageset/icons8-edit-file-100_white.png
  OneDayOneAnswer/OneDayOneAnswer/Assets.xcassets/to_edit_white.imageset/icons8-pencil-drawing-100_white.png
  OneDayOneAnswer/OneDayOneAnswer/Assets.xcassets/to_list.imageset/Contents.json
  OneDayOneAnswer/OneDayOneAnswer/Assets.xcassets/to_list.imageset/icons8-top-menu-100.png
  OneDayOneAnswer/OneDayOneAnswer/Assets.xcassets/to_list_white.imageset/Contents.json
  OneDayOneAnswer/OneDayOneAnswer/Assets.xcassets/to_list_white.imageset/icons8-bulleted-list-100_white.png
  OneDayOneAnswer/OneDayOneAnswer/Assets.xcassets/to_list_white.imageset/icons8-top-menu-100_white.png
  OneDayOneAnswer/OneDayOneAnswer/Assets.xcassets/to_photolibrary.imageset/Contents.json
  OneDayOneAnswer/OneDayOneAnswer/Assets.xcassets/to_photolibrary.imageset/icons8-pictures-folder-100.png
  OneDayOneAnswer/OneDayOneAnswer/Assets.xcassets/to_save.imageset/Contents.json
  OneDayOneAnswer/OneDayOneAnswer/Assets.xcassets/to_save.imageset/icons8-checkmark-100.png
  OneDayOneAnswer/OneDayOneAnswer/Assets.xcassets/to_save_disabled.imageset/icons8-checkmark-100_gray.png
  OneDayOneAnswer/OneDayOneAnswer/Assets.xcassets/to_save_gray.imageset/Contents.json
  OneDayOneAnswer/OneDayOneAnswer/Assets.xcassets/to_save_gray.imageset/icons8-checkmark-100_disabled (1).png
  OneDayOneAnswer/OneDayOneAnswer/Base.lproj/Today.storyboard
  OneDayOneAnswer/OneDayOneAnswer/Display.storyboard
  OneDayOneAnswer/OneDayOneAnswer/DisplayViewController.swift
  OneDayOneAnswer/OneDayOneAnswer/List.storyboard
  OneDayOneAnswer/OneDayOneAnswer/ListViewController.swift
  OneDayOneAnswer/OneDayOneAnswer/TodayViewController.swift
Labels: 뷰컨트롤러 구현

#72 Feature/database
  OneDayOneAnswer/OneDayOneAnswer/42-JMJ-Question.tsv
  OneDayOneAnswer/OneDayOneAnswer/DataBase/SqliteDataBase.swift
Labels: 개발, 데이터베이스, 버그
