Repository 42-JMJ/iOS-App-Project, pull requests merged in 2020-04, with the labels that each got.

#4 add gitignore
  .gitignore
Labels: 협업환경

#7 Xcode 프로젝트 및 스토리보드 생성
  OneDayOneAnswer/OneDayOneAnswer.xcodeproj/project.pbxproj
  OneDayOneAnswer/OneDayOneAnswer.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  OneDayOneAnswer/OneDayOneAnswer.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  OneDayOneAnswer/OneDayOneAnswer/AppDelegate.swift
  OneDayOneAnswer/OneDayOneAnswer/Assets.xcassets/AppIcon.appiconset/Contents.json
  OneDayOneAnswer/OneDayOneAnswer/Assets.xcassets/Contents.json
  OneDayOneAnswer/OneDayOneAnswer/Base.lproj/LaunchScreen.storyboard
  OneDayOneAnswer/OneDayOneAnswer/Info.plist
  OneDayOneAnswer/OneDayOneAnswer/Storyboard/Base.lproj/Main.storyboard
  OneDayOneAnswer/OneDayOneAnswer/Storyboard/Sub1.storyboard
  OneDayOneAnswer/OneDayOneAnswer/Storyboard/Sub2.storyboard
  OneDayOneAnswer/OneDayOneAnswer/Storyboard/Sub3.storyboard
  OneDayOneAnswer/OneDayOneAnswer/Sub.stroyboard1.storyboard
  OneDayOneAnswer/OneDayOneAnswer/ViewController.swift
Labels: 협업환경

#15 프로젝트 재생성 및 스토리보드 상호간 연결
  OneDayOneAnswer/OneDayOneAnswer.xcodeproj/project.pbxproj
  OneDayOneAnswer/OneDayOneAnswer/AppDelegate.swift
  OneDayOneAnswer/OneDayOneAnswer/Base.lproj/Today.storyboard
  OneDayOneAnswer/OneDayOneAnswer/Info.plist
  OneDayOneAnswer/OneDayOneAnswer/List.storyboard
  OneDayOneAnswer/OneDayOneAnswer/ListViewController.swift
  OneDayOneAnswer/OneDayOneAnswer/SelectedDay.storyboard
  OneDayOneAnswer/OneDayOneAnswer/SelectedDayViewController.swift
  OneDayOneAnswer/OneDayOneAnswer/Storyboard/Base.lproj/Main.storyboard
  OneDayOneAnswer/OneDayOneAnswer/Storyboard/Sub1.storyboard
  OneDayOneAnswer/OneDayOneAnswer/Storyboard/Sub2.storyboard
  OneDayOneAnswer/OneDayOneAnswer/Storyboard/Sub3.storyboard
  OneDayOneAnswer/OneDayOneAnswer/Sub.stroyboard1.storyboard
  OneDayOneAnswer/OneDayOneAnswer/TodayViewController.swift
  OneDayOneAnswer/Podfile
Labels: 협업환경

#20 Today.Storayboard 구현(1)
  OneDayOneAnswer/OneDayOneAnswer/Base.lproj/Today.storyboard
  OneDayOneAnswer/OneDayOneAnswer/TodayViewController.swift
Labels: 뷰컨트롤러

#23 DataBase protocol과 Article struct 선언
  OneDayOneAnswer/OneDayOneAnswer.xcodeproj/project.pbxproj
  OneDayOneAnswer/OneDayOneAnswer/DataBase/DataBase.swift
  OneDayOneAnswer/OneDayOneAnswer/DataBase/TestDB.swift
Labels: 데이터베이스

#25 Today.Storayboard 구현(2)
  OneDayOneAnswer/OneDayOneAnswer/Base.lproj/Today.storyboard
  OneDayOneAnswer/OneDayOneAnswer/TodayViewController.swift
Labels: 뷰컨트롤러

#27 Feature/database
  OneDayOneAnswer/OneDayOneAnswer.xcodeproj/project.pbxproj
  OneDayOneAnswer/OneDayOneAnswer/DataBase/DataBase.swift
  OneDayOneAnswer/OneDayOneAnswer/DataBase/SqliteDataBase.swift
  OneDayOneAnswer/OneDayOneAnswer/DataBase/TestDataBase.swift
Labels: 데이터베이스

#28 Feature/list
  OneDayOneAnswer/OneDayOneAnswer.xcodeproj/project.pbxproj
  OneDayOneAnswer/OneDayOneAnswer/AppDelegate.swift
  OneDayOneAnswer/OneDayOneAnswer/Assets.xcassets/bbb.imageset/Contents.json
  OneDayOneAnswer/OneDayOneAnswer/Assets.xcassets/bbb.imageset/bbb.jpg
  OneDayOneAnswer/OneDayOneAnswer/Assets.xcassets/cat_chair_launch_screen.imageset/Contents.json
  OneDayOneAnswer/OneDayOneAnswer/Assets.xcassets/cat_chair_launch_screen.imageset/cat_chair_launch_screen.jpeg
  OneDayOneAnswer/OneDayOneAnswer/Assets.xcassets/coffee_books_launch_screen.imageset/Contents.json
  OneDayOneAnswer/OneDayOneAnswer/Assets.xcassets/coffee_books_launch_screen.imageset/coffee_books_launch_screen.jpg
  OneDayOneAnswer/OneDayOneAnswer/Assets.xcassets/ehud-neuhaus-xA-CZRmja3o-unsplash.imageset/Contents.json
  OneDayOneAnswer/OneDayOneAnswer/Assets.xcassets/night_sky_launch_screen.imageset/Contents.json
  OneDayOneAnswer/OneDayOneAnswer/Assets.xcassets/night_sky_launch_screen.imageset/night_sky_launch_screen.jpeg
  OneDayOneAnswer/OneDayOneAnswer/Assets.xcassets/top-view-photo-of-people-writing-on-notebook-1557251.imageset/Contents.json
  OneDayOneAnswer/OneDayOneAnswer/Assets.xcassets/top-view-photo-of-people-writing-on-notebook-1557251.imageset/top-view-photo-of-people-writing-on-notebook-1557251.jpg
  OneDayOneAnswer/OneDayOneAnswer/Base.lproj/LaunchScreen.storyboard
  OneDayOneAnswer/OneDayOneAnswer/List.storyboard
  OneDayOneAnswer/OneDayOneAnswer/ListViewController.swift
  OneDayOneAnswer/OneDayOneAnswer/TableViewCell.swift
Labels: 뷰컨트롤러

#30 Today.Storayboard 구현(3)
  OneDayOneAnswer/OneDayOneAnswer.xcodeproj/project.pbxproj
  OneDayOneAnswer/OneDayOneAnswer/Base.lproj/Today.storyboard
  OneDayOneAnswer/OneDayOneAnswer/DataBase/TestDataBase.swift
  OneDayOneAnswer/OneDayOneAnswer/Display.storyboard
  OneDayOneAnswer/OneDayOneAnswer/DisplayViewController.swift
  OneDayOneAnswer/OneDayOneAnswer/List.storyboard
  OneDayOneAnswer/OneDayOneAnswer/TodayViewController.swift
Labels: 뷰컨트롤러

#32 Feature/database
  OneDayOneAnswer/OneDayOneAnswer/DataBase/DataBase.swift
  OneDayOneAnswer/OneDayOneAnswer/DataBase/SqliteDataBase.swift
  OneDayOneAnswer/OneDayOneAnswer/DataBase/TestDataBase.swift
Labels: 데이터베이스
